### ISSUE TITLE
Parameterized type constructed incorrectly for nested types

### ISSUE THREAD

**Issue by nedtwigg** [rharter/auto-value-moshi#102]
I have a domain model with deep generics:

```java
public abstract class Model {
    public abstract ImmutableList<A<B<C<Long>>>> field();
```

The code that gets generated has a bug:

```java
final class AutoValue_Model extends $AutoValue_Model {
  public static final class MoshiJsonAdapter extends JsonAdapter<Model> {
    private final JsonAdapter<ImmutableList<A<B<C<Long>>>>> fieldAdapter;
    public MoshiJsonAdapter(Moshi moshi) {
Actual: this.fieldAdapter = moshi.adapter(Types.newParameterizedType(ImmutableList.class, Types.newParameterizedType(A.class, Types.newParameterizedType(B.class, Types.newParameterizedType(C.class, Long.class)))));
Needed: this.fieldAdapter = moshi.adapter(Types.newParameterizedType(ImmutableList.class, Types.newParameterizedTypeWithOwner(ImmutableList.class, A.class, Types.newParameterizedType(B.class, Types.newParameterizedTypeWithOwner(B.class, C.class, Long.class)))));
```

When I run the code that actually gets generated by `0.4.4`, I get:

```
java.lang.IllegalArgumentException: unexpected owner type for class com.mycompany.C: null
	at com.squareup.moshi.Types$ParameterizedTypeImpl.<init>(Types.java:509)
	at com.squareup.moshi.Types.newParameterizedType(Types.java:75)
	at com.mycompany.AutoValue_Model$MoshiJsonAdapter
```

I figured out "Needed" by fixing one error at a time.  The strange thing is that `A` and `C` needed to be created with `Types.newParameterizedTypeWithOwner(`, but it was okay to create `B` with just `Types.newParameterizedType`.

I dunno why :man_shrugging:.  It's probably ill-advised to have generics this deep, I'm going to fix by reducing the nesting, but figured it was worth a bug report in case other people have this error.

**Comment by rharter** [comment]
Honestly I don't even know what `Types.newParameterizedTypeWithOwner` is.  @swankjesse or @JakeWharton, any insight?

**Comment by NightlyNexus** [comment]
It's for nested types.
```java
class Foo {
  class Bar<T> {
  }
}
Types.newParameterizedTypeWithOwner(Foo.class, Bar.class, String.class)
```

so it depends on where the A, B, C classes are nested.

**Comment by nedtwigg** [comment]
Aha!  That explains it.  Sorry, my `<A<B<C<Long>>>>` didn't capture all of the relevant info.  Great inference!  Two surprising things:

1) the classes in question are all static.  so it's:

```java
class Foo {
  static class Bar<T> {
```

2) the owner types that I supplied are all wrong, but it works.

The [constructor of ParameterizedTypeImpl requires an owner type for static inner classes](https://github.com/square/moshi/blob/ed1ea5a755aaa739f2bc91991e32dd6e32a08267/moshi/src/main/java/com/squareup/moshi/Types.java#L504-L510), but doesn't care if it's the right class or not.  I've spent the whole day showing the moshi team that I don't understand what's going on ;-)  But this seems a bit off.  Either ParameteredTypeImpl shouldn't need an owner class for static enclosed classes (seems right to me), or if it's gonna require an owner, maybe it oughtta check that it's the right owner?

**Comment by NightlyNexus** [comment]
If you pass in the wrong owner type, you will get subtle errors when checking equality of Types.
Good spot; I opened https://github.com/square/moshi/pull/450 to fail explicitly and earlier in the common case.

**Comment by nedtwigg** [comment]
So if a type is nested (which we can check with `Class.getEnclosingType`) then we should create it with `Types.newParameterizedTypeWithOwner` rather than `Types.newParameterizedType`.  I'd be happy to provide a PR, but I'm stuck on an old version by #99.  I'll stay subbed, in case we figure out a way to resolve #99.

**Comment by JakeWharton** [comment]
We should be able to determine that at compilation time, not runtime.

**Comment by ZacSweers** [comment]
Is this actually something we should support? As opposed to just saying the inner classes should also be static. Thinking out loud, but it it seems weird to me that a subset of the nested json data would have any requirements of the java ownership of the class consuming it. I'm kind of in favor of voting just requiring inner classes to be static (with a descriptive error), but open to hear arguments in favor of non-static inner classes

**Comment by nedtwigg** [comment]
I agree that only supporting static inner classes is the right call.  However, inner classes of any kind currently not supported, static or not.

**Comment by ZacSweers** [comment]
Isn't `newParameterizedTypeWithOwner` only for non-static inner classes?

**Comment by nedtwigg** [comment]
That was not [my experience](https://github.com/rharter/auto-value-moshi/issues/102#issuecomment-367935499).

**Comment by NightlyNexus** [comment]
>Isn't newParameterizedTypeWithOwner only for non-static inner classes?

No. It's for nested classes.

**Comment by ZacSweers** [comment]
I'm using `newParameterizedTypeWithOwner` without issue here: https://github.com/rharter/auto-value-moshi/pull/146/commits/1c5e6f89975b40875a9237451f406e7a99f0e63d

As such I'm going to close this as static inner classes do work
