### ISSUE TITLE
Retrofit's MoshiRequestBodyConverter doesn't use the generated type adapters

### ISSUE THREAD

**Issue by vibin** [rharter/auto-value-moshi#103]
Hi, while migrating from auto-value-gson to auto-value-moshi, I've realized the latter doesn't play well with `MoshiRequestBodyConverter`.

I've a simple AutoValue class which has the `typeAdapter(Moshi)` method exposed - I can confirm that its fromJson is getting called while response is being deserialized, but the toJson is not called during serialization.

That is, Moshi's `ClassJsonAdapter` is being picked up instead of the generated TypeAdapter from the switch-case in `AutoValueMoshi_AutoValueMoshiTypeAdapterFactory`. I'm guessing this is because I'm passing in a `AutoValue_Foo` class in my body and the switch-case returns null instead of returning `TypeAdapter<Foo>`.

I found a relevant commit which was reverted: https://github.com/rharter/auto-value-moshi/commit/57e0d1d4d5183ac99ced35b2ed2f2b00f337200e

**Comment by NightlyNexus** [comment]
>I'm passing in a AutoValue_Foo class in my body and the switch-case returns null instead of returning TypeAdapter<Foo>.

You want the Retrofit service to look up an adapter for Foo, not AutoValue_Foo. Use something like `retrofit2.Call<Foo>` instead of `retrofit2.Call<AutoValue_Foo>`.
What's your service method look like?

**Comment by vibin** [comment]
My service looks like `Call<Void> bar(@Body Map<String, Object> body)`.

And my calling code like:
```java
List<Foo> foos = singletonList(Foo.create());
service.bar(mapOf("foos", foos));
```

I've spent some time stepping through the code in debugger and I think (pls correct me if I'm wrong) Moshi is using `ObjectJsonAdapter`, which does a .getClass() on the value object which returns an `AutoValue_Foo` class.

**Comment by vibin** [comment]
I think this can solved by using `@Body Map<String, Foo>`, but I do want the value generic argument to be Object, not Foo - because I want to put other entries with value types like String, Integer etc into this container.

**Comment by rharter** [comment]
You'll have to create your own type adapter to identify the types there.
Since you're providing an Object there really isn't a way for Moshi to
handle this.

**Comment by vibin** [comment]
Okay, I'll try that...but serializing AutoValue objects as Object worked in Gson/auto-value-gson, where the generated TypeAdapterFactory uses `Class#isAssignableFrom(Class)` to match classes - so a `TypeAdapter<Foo>` would be returned for `AutoValue_Foo`.

**Comment by vibin** [comment]
I think this can be solved by using a custom type adapter, but any reason why auto-value-moshi's class matching logic (in `AutoValueMoshi_AutoValueMoshiTypeAdapterFactory`) is different from that of auto-value-gson?
