### ISSUE TITLE
Generated constructor strips all annotations for parameters

### ISSUE THREAD

**Issue by saket** [rharter/auto-value-moshi#104]
Will it be possible to read annotations on property methods and include annotations for constructor parameters? auto-value-moshi currently strips all annotations rendering IDE inspections unusable on them. The constructors generated by auto-value on the other hand include them as expected.

**Comment by ZacSweers** [comment]
Can do

**Comment by ZacSweers** [comment]
Actually looks like this was already done #111

Feel free to comment if you meant more than just nullability annotations

**Comment by saket** [comment]
I do think that it'll be nice if all annotations get carried over, but I'll let others voice in if they want to see this feature. I've now moved to moshi codegen so I no longer need this. :)
