### ISSUE TITLE
Keeping track of unknown properties

### ISSUE THREAD

**Issue by mattbdean** [rharter/auto-value-moshi#109]
I maintain a wrapper for an API that is constantly adding new properties to their models. Right now the only way to provide the consumers of my library access to these new properties is to add new methods and release another version. I'd like the time between the API introducing a new property and the consumers of my library being able to use those properties to be as small as possible.

**How it would work**

1. Add an abstract an abstract method annotated with `@UnknownProperties` that returns a `Map<String, Object>`.

```diff
@AutoValue
public abstract class Foo {
    public abstract String getBar();
    public abstract String getBaz();

+   @UnknownProperties
+   public abstract Map<String, Object> getUnknownProperties();

    public static JsonAdapter<Foo> jsonAdapter(Moshi moshi) {
        return new AutoValue_Foo.MoshiJsonAdapter(moshi);
    }
}
```

2. The generated JsonAdapter would be slightly different

```diff
final class AutoValue_Foo extends $AutoValue_Foo {
  AutoValue_Foo(String bar, String baz, Map<String, Object> unknownProperties) {
    super(bar, baz, unknownProperties);
  }

  public static final class MoshiJsonAdapter extends JsonAdapter<Foo> {
-   private static final String[] NAMES = new String[] {"bar","baz","unknownProperties"};
+   private static final String[] NAMES = new String[] {"bar","baz"};
    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);
    private final JsonAdapter<String> barAdapter;
    private final JsonAdapter<String> bazAdapter;
-   private final JsonAdapter<Map<String, Object>> unknownPropertiesAdapter;
+   private final JsonAdapter<Object> unknownPropertiesAdapter;
    public MoshiJsonAdapter(Moshi moshi) {
      this.barAdapter = adapter(moshi, String.class);
      this.bazAdapter = adapter(moshi, String.class);
-     this.unknownPropertiesAdapter = adapter(moshi, Types.newParameterizedType(Map.class, String.class, Object.class));
+     this.unknownPropertiesAdapter = adapter(moshi, Object.class);
    }
    @Override
    public Foo fromJson(JsonReader reader) throws IOException {
      reader.beginObject();
      String bar = null;
      String baz = null;
-     Map<String, Object> unknownProperties = null;
+     Map<String, Object> unknownProperties = new HashMap<String, Object>();
      while (reader.hasNext()) {
        switch (reader.selectName(OPTIONS)) {
          case 0: {
            bar = this.barAdapter.fromJson(reader);
            break;
          }
          case 1: {
            baz = this.bazAdapter.fromJson(reader);
            break;
          }
          case -1: {
-           // Unknown name, skip it
-           reader.nextName();
-           reader.skipValue();
+           // Unknown name, store it
+           unknownProperties.put(reader.nextName(), reader.readJsonValue());
          }
        }
      }
      reader.endObject();
      return new AutoValue_Foo(bar, baz, unknownProperties);
    }
    @Override
    public void toJson(JsonWriter writer, Foo value) throws IOException {
      writer.beginObject();
      writer.name("bar");
      this.barAdapter.toJson(writer, value.getBar());
      writer.name("baz");
      this.bazAdapter.toJson(writer, value.getBaz());
-     writer.name("unknownProperties");
-     this.unknownPropertiesAdapter.toJson(writer, value.getUnknownProperties());
+     for (Map.Entry<String, Object> entry : value.getUnknownProperties().entrySet()) {
+       writer.name(entry.getKey());
+       unknownPropertiesAdapter.toJson(writer, entry.getValue());
+     }
      writer.endObject();
    }
    private JsonAdapter adapter(Moshi moshi, Type adapterType) {
      return moshi.adapter(adapterType);
    }
  }
}
```

3. Deserialize JSON

```json
{
  "bar": "some value",
  "baz": "another value",
  "something": 42
}
```

```java
JsonAdapter<Foo> adapter = ...
Foo foo = adapter.fromJson(json);
foo.getUnknownProperties().get("something"); // == 42
```

I'd be happy to send a PR if this is something you want to have.

**Comment by rharter** [comment]
Thanks @mattbdean.  I know protobuf does stuff like this, but I'd be really interested to hear the general philosophy of @JakeWharton and @swankjesse on this.  Does Moshi have any sort of opinion on this type of thing?

**Comment by mattbdean** [comment]
I'm not too sure. I'll open an issue and find out

**Comment by JakeWharton** [comment]
I don't understand why the map is a property of the adapter. That would cause properties from all objects to combine together. Did you mean for that to be a local in each method?

**Comment by mattbdean** [comment]
You're right, that should be a local variable

**Comment by JakeWharton** [comment]
In general with regard to the feature, there's nothing specific about auto-value-moshi here. One could argue this as a general feature of Moshi even for reflective use.
```java
class Foo {
  @UnknownProperties Map<String, Object> unknown;
  String bar;
  String baz;
}
```
Then auto-value-moshi would just honor the annotation in the same way with its generated adapters.

As to whether or not such a feature is something that _should_ be in Moshi I don't know.

**Comment by mattbdean** [comment]
@NightlyNexus seems to feel this feature isn't going to get a lot of use and performance would suffer if its built into ClassJsonAdapter.

**Comment by swankjesse** [comment]
You could build a custom adapter to do it. `JsonReader.readJsonValue()` is your friend!

**Comment by mattbdean** [comment]
Unless I'm missing something, I'd have to ditch auto-value-moshi entirely if I went the custom adapter route.

**Comment by mattbdean** [comment]
I'd like to work on a PR if everyone thinks this is the right place to implement this feature.

**Comment by ZacSweers** [comment]
@mattbdean I don't think this is the right place, but I believe you could do this by creating a delegating JsonReader subclass, record read names, and then correlate them to when `skipValue()` is called. I'm not sure how a custom adapter approach would cover this as readJsonValue() would not tell you which ones aren't used.
