### ISSUE TITLE
Unresolved reference for AutoValue MoshiJsonAdapter

### ISSUE THREAD

**Issue by MichaelReyes** [rharter/auto-value-moshi#132]
Hi, my project can't build when I migrated to Kotlin because of this 'Unresolved reference AutoValueMoshi_ModelAdapterFactory'

`@AutoValue
abstract class Repo {

    abstract fun id(): Long
    abstract fun name(): String
    abstract fun description(): String?
    abstract fun owner(): User
    @Json(name = "stargazers_count")
    abstract fun stars(): Long

    @Json(name = "forks_count")
    abstract fun forks(): Long

    companion object {

        @JvmStatic fun moshiAdapter(moshi: Moshi): JsonAdapter<Repo>{
            return AutoValue_Repo.MoshiJsonAdapter(moshi)
        }
    }
}`

![image](https://user-images.githubusercontent.com/13358867/55975853-6d124900-5cbd-11e9-9c45-62ea891b19e6.png)

**Comment by ZacSweers** [comment]
I believe this is a misconfiguration with your project/kapt, not an auto-value-moshi issue. Please feel free to reopen though if you can link a reproducible sample
