### ISSUE TITLE
Unable to build when implement the generic class

### ISSUE THREAD

**Issue by KKChong** [rharter/auto-value-moshi#136]
how to use the generic class?
i got this error when build -> error: non-static type variable T cannot be referenced from a static context

**Comment by ZacSweers** [comment]
Can you provide a code snippet? That's not enough information for us to be able to help

**Comment by KKChong** [comment]
i think the readme quite misleading. Under the section the "Generics Support"

the static method should be :
public static <T> JsonAdapter<Foo<T>> jsonAdapter(Moshi moshi, Type[] types)

instead of: 
public static JsonAdapter<Foo<T>> jsonAdapter(Moshi moshi, Type[] types) {

**Comment by KKChong** [comment]
i think the readme quite misleading under the "Generics Support"

`public static <T> JsonAdapter<Foo<T>> jsonAdapter(Moshi moshi, Type[] types)`

instead of 

`public static JsonAdapter<Foo<T>> jsonAdapter(Moshi moshi, Type[] types)`

**Comment by rharter** [comment]
Thanks for catching that.  Care to submit a PR with the update?

**Comment by ZacSweers** [comment]
Fixed with #141
