### ISSUE TITLE
Support of default values using builders

### ISSUE THREAD

**Issue by david-gang** [rharter/auto-value-moshi#137]
This issue is maybe covered in #20 but is closed. 
From AutoValue 1.7 the builder api is available, which makes it possible to set default values using builders. 
This is already implemented in autovalue-gson from this commit: https://github.com/rharter/auto-value-gson/commit/a1aa36ebcd3baf770840fc3c603f6db328e7ca24. 
Can this also be implemented in autovalue-moshi?

**Comment by david-gang** [comment]
Hi @rharter , Are prs welcome ? I could give it try as the gson solution is very close to what we will need here but i want to be sure that this pr will get be reviewed by someone.

Thanks

**Comment by ZacSweers** [comment]
Pr welcome!

**Comment by david-gang** [comment]
This could be closed because it was already implemented by https://github.com/rharter/auto-value-moshi/commit/54b1952d88578def0c455a96942b32037c60e685

Could a new version please released?

**Comment by ZacSweers** [comment]
It's a holiday week here in the states and this project is maintained in our free time. Please be patient

**Comment by david-gang** [comment]
> It's a holiday week here in the states and this project is maintained in our free time. Please be patient

Will wait. Wanted to remind that i have also some merits in the production of the  last version :-)
I am not nudging without doing anything to improve the situation.

**Comment by david-gang** [comment]
@ZacSweers kindly reminder. i invested quite reasonable time in the PRs and i want to get it into a release. is there a timeline when you plan the next release?

**Comment by rharter** [comment]
Sorry about that, @david-gang, I'll take a look this week at what we can do to get something out.
