### ISSUE TITLE
please publish auto-value-moshi-runtime:

### ISSUE THREAD

**Issue by david-gang** [rharter/auto-value-moshi#167]
Per documentation we should add these dependencies:
```
annotationProcessor("com.ryanharter.auto.value:auto-value-moshi-extension:1.0.0")
implementation("com.ryanharter.auto.value:auto-value-moshi-runtime:1.0.0")
```

I cannot find this artifact: https://mvnrepository.com/artifact/com.ryanharter.auto.value/auto-value-moshi-runtime

Please publish it
Thanks for the great advance in this project

**Comment by ZacSweers** [comment]
Looks like it was accidentally still published as `auto-value-moshi-annotations`. You can use that for now and we’ll fix the artifact name in the next release

**Comment by ZacSweers** [comment]
Side note - that site is a 3rd party site and not a source of truth. You should use https://repo1.maven.org/maven2/com/ryanharter/auto/value/ as a reference for artifacts
