### ISSUE TITLE
Gradle runtime dependency name incorrect in README.md

### ISSUE THREAD

**Issue by joelightshoe** [rharter/auto-value-moshi#169]
The Readme for 1.0.0 specifies the gradle runtime dependency
```
implementation("com.ryanharter.auto.value:auto-value-moshi-runtime:1.0.0")
```
but the dependency name should be ```auto-value-moshi-annotations``` instead of ```auto-value-moshi-runtime``` based on what is available on [mvnrepository.com](https://mvnrepository.com/artifact/com.ryanharter.auto.value/auto-value-moshi-annotations).

**Comment by ZacSweers** [comment]
Known issue and will be fixed in the next release. Please search the issue tracker before posting
