### ISSUE TITLE
please upload new snapshot version to maven.

### ISSUE THREAD

**Issue by david-gang** [rharter/auto-value-moshi#172]
Hi.

Would it be possible to upload a new snapshot version to sonatype?
https://oss.sonatype.org/content/repositories/snapshots/com/ryanharter/auto/value/
i had bugs in version 1 which were fixed but i cannot check if i find additional bugs.
Thanks

**Comment by ZacSweers** [comment]
Why can’t you install locally?

**Comment by david-gang** [comment]
will try. thanks.

**Comment by david-gang** [comment]
it failed 


>./gradlew install
> Task :auto-value-moshi-extension:shadowJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':auto-value-moshi-extension:shadowJar'.
> neither file nor directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by david-gang** [comment]
Hi, Any update on this issue please?

**Comment by david-gang** [comment]
Hi, Is there any update?
Can a new version please be released?

Thanks

**Comment by ZacSweers** [comment]
I don't know why your local install isn't working but I'm going to close this out for now. Issue tracking isn't the right place for requests like this

**Comment by david-gang** [comment]
what is the suggested forum of asking this please? 
Besides this there is already a fix in master and this request is waiting for 1 year now already. When is the next release planned.
I don't use this library now for new projects as i switched to kotlin and just have this library in legacy projects but anyway it would be nice to know when the next release is planned and if no future release is planned it would also be nice to have a mesaage at readme.md that this project is no longer maintained.

**Comment by ZacSweers** [comment]
Asking for new releases or ETAs are pretty universally discouraged across the FOSS space. Inquiring about the state of the project or make feature requests or file issues about the project itself is ok, but opening dedicated issues to ask for new releases is not. It’s really important to understand that you’re not entitled to a release or snapshots in OSS, let alone when it’s just due to you not being able to build from source yourself.
