### ISSUE TITLE
Parcelable auto value entities are being generated incorrectly with the 1.0.0 version

### ISSUE THREAD

**Issue by hakanbagci** [rharter/auto-value-moshi#173]
When updating auto value moshi dependencies from `0.4.7` to `1.0.0` the auto value entities which are marked as `Parcelable` started failing (does not compile). Tests are done using the latest version (`0.2.8`) of `auto-parcel`. It seems that new version (`1.0.0`) is adding redundant `$` sign while calling a constructor in one of the generated classes.

Here is a simple auto value class:
```java
@AutoValue
public abstract class Foo implements Parcelable {
    abstract String bar();

    public static JsonAdapter<Foo> jsonAdapter(Moshi moshi) {
        return new AutoValue_Foo.MoshiJsonAdapter(moshi);
    }
}
```

Here is the generated `$AutoValue_Foo` class: 
A comment is added to the line that has the wrong constructor call. It seems that `$AutoValue_Foo(bar)` should be `AutoValue_Foo(bar)`.
```java
abstract class $AutoValue_Foo extends $$AutoValue_Foo {
  $AutoValue_Foo(String bar) {
    super(bar);
  }

  public static final class MoshiJsonAdapter extends JsonAdapter<Foo> {
    private static final String[] NAMES = new String[] {"bar"};
    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);
    private final JsonAdapter<String> barAdapter;
    public MoshiJsonAdapter(Moshi moshi) {
      this.barAdapter = moshi.adapter(String.class).nonNull();
    }
    @Override
    public Foo fromJson(JsonReader reader) throws IOException {
      reader.beginObject();
      String bar = null;
      while (reader.hasNext()) {
        switch (reader.selectName(OPTIONS)) {
          case 0: {
            bar = this.barAdapter.fromJson(reader);
            break;
          }
          case -1: {
            // Unknown name, skip it
            reader.skipName();
            reader.skipValue();
          }
        }
      }
      reader.endObject();
      return new $AutoValue_Foo(bar); // $AutoValue_Foo(bar) -> AutoValue_Foo(bar)
    }
    @Override
    public void toJson(JsonWriter writer, Foo value) throws IOException {
      writer.beginObject();
      writer.name("bar");
      this.barAdapter.toJson(writer, value.bar());
      writer.endObject();
    }
    @Override
    public String toString() {
      return new StringBuilder().append("JsonAdapter(").append("Foo").append(")").toString();
    }
  }
}
```

Here is the generated code with old version (`0.4.7`) using the same auto value class definition.
```java
abstract class $AutoValue_Foo extends $$AutoValue_Foo {
  $AutoValue_Foo(String bar) {
    super(bar);
  }

  public static final class MoshiJsonAdapter extends JsonAdapter<Foo> {
    private static final String[] NAMES = new String[] {"bar"};
    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);
    private final JsonAdapter<String> barAdapter;
    public MoshiJsonAdapter(Moshi moshi) {
      this.barAdapter = adapter(moshi, String.class);
    }
    @Override
    public Foo fromJson(JsonReader reader) throws IOException {
      reader.beginObject();
      String bar = null;
      while (reader.hasNext()) {
        switch (reader.selectName(OPTIONS)) {
          case 0: {
            bar = this.barAdapter.fromJson(reader);
            break;
          }
          case -1: {
            // Unknown name, skip it
            reader.skipName();
            reader.skipValue();
          }
        }
      }
      reader.endObject();
      return new AutoValue_Foo(bar); // This is correct constructor call
    }
    @Override
    public void toJson(JsonWriter writer, Foo value) throws IOException {
      writer.beginObject();
      writer.name("bar");
      this.barAdapter.toJson(writer, value.bar());
      writer.endObject();
    }
    private JsonAdapter adapter(Moshi moshi, Type adapterType) {
      return moshi.adapter(adapterType);
    }
  }
}
```

**Comment by rharter** [comment]
This looks to be an issue here:
https://github.com/rharter/auto-value-moshi/blob/master/auto-value-moshi-extension/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java#L733

That line should be using the autoValueClassName, not the className. I'm on
the road for the weekend so can't take care of it, but PRs are welcome.

**Comment by hakanbagci** [comment]
@rharter Thanks for the fix recommendation. Using `autoValueClassName` does not seem to fix the problem. I have checked the `createReadMethod` from `AutoValueMoshiExtension.java` in version `0.4.7`.  I applied the similar approach from the following line and it seems that it fixes the problem.

https://github.com/rharter/auto-value-moshi/blob/ef6bcd70733e3570c7ee070d30bdea918003ce87/auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java#L548

**Comment by ZacSweers** [comment]
I think auto-value-moshi is working as intended here. It's hard to say as your issue seems to be with whatever "auto-parcel" is, but we are just invoking the constructor we generated. Can you give the full error and why it should be trying to shortcut to a class name we're not given? That's fairly brittle and almost certainly not correct in the way you have PR'd it.

**Comment by hakanbagci** [comment]
@ZacSweers I understand that this in not the perfect solution. This was the working solution in `0.4.7` and I have just copied it to here. Here is the link to the working solution. 

https://github.com/rharter/auto-value-moshi/blob/ef6bcd70733e3570c7ee070d30bdea918003ce87/auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java#L548

Since you have better know-how in `auto-value-moshi` and `auto-value_parcel` it would be better you propose a better solution. But it is kinda obvious that when `AutoValueMoshiExtension` class is rewritten it is broken because the outputs are not same any more. You can check again the outputs  of `0.4.7` and `1.0.0` from the first comment. 

I think `auto-value-moshi` should not make an assumption about single hierarchy. There might be other abstract classes in the hierarchy while generating the code as in the case of `Parcelable`s. 

Here is the full error code (Compile error) when I try to generate code for the Foo class in first comment.

```
.../entity/$AutoValue_Foo.java:42: error: $AutoValue_Foo is abstract; cannot be instantiated
      return new $AutoValue_Foo(bar);
             ^
``` 

Here is the generated class:

```java
package de.meinfernbus.network.entity;

import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.JsonReader;
import com.squareup.moshi.JsonWriter;
import com.squareup.moshi.Moshi;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;

abstract class $AutoValue_Foo extends $$AutoValue_Foo {
  $AutoValue_Foo(String bar) {
    super(bar);
  }

  public static final class MoshiJsonAdapter extends JsonAdapter<Foo> {
    private static final String[] NAMES = new String[] {"bar"};
    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);
    private final JsonAdapter<String> barAdapter;
    public MoshiJsonAdapter(Moshi moshi) {
      this.barAdapter = moshi.adapter(String.class).nonNull();
    }
    @Override
    public Foo fromJson(JsonReader reader) throws IOException {
      reader.beginObject();
      String bar = null;
      while (reader.hasNext()) {
        switch (reader.selectName(OPTIONS)) {
          case 0: {
            bar = this.barAdapter.fromJson(reader);
            break;
          }
          case -1: {
            // Unknown name, skip it
            reader.skipName();
            reader.skipValue();
          }
        }
      }
      reader.endObject();
      return new $AutoValue_Foo(bar);
    }
    @Override
    public void toJson(JsonWriter writer, Foo value) throws IOException {
      writer.beginObject();
      writer.name("bar");
      this.barAdapter.toJson(writer, value.bar());
      writer.endObject();
    }
    @Override
    public String toString() {
      return new StringBuilder().append("JsonAdapter(").append("Foo").append(")").toString();
    }
  }
}

```

It should not call `$AutoValue_Foo(bar)` but `AutoValue_Foo(bar)` in return statement of `fromJson` method.

**Comment by ZacSweers** [comment]
I see. And there's no way to get AutoValue_Foo from the auto value extension API? That would be surprising

**Comment by hakanbagci** [comment]
> I see. And there's no way to get AutoValue_Foo from the auto value extension API? That would be surprising

@ZacSweers Actually I could not find a way to get the correct class name in a better way. If I am not mistaken, in current context  `className`  is `$AutoValue_Foo` and `autoValueClassName` is `Foo`, but we are looking for `AutoValue_Foo`. I think removing the leading `$`s looks like a solution since it is guaranteed that it will not call the abstract class constructor in any case , but I accept that is not the best.

**Comment by ZacSweers** [comment]
Thing is we're not guaranteed That the one without the dollar signs is it

**Comment by hakanbagci** [comment]
I am assuming that the purpose of `auto-value` and `auto-value-moshi` is to generate a concrete class in the end which does not start with `$`. As far as I see from generated code all abstract classes start with `$`, but only final class does not start with `$`.  I think this implies that if we want to create an instance at some point it should be the class without `$`.  To be specific to our case, the only concrete class in the hierarchy is `AutoValue_Foo` in all the scenarios whether we have extra `Parcelable` hierarchy or not. 

As a summary, classes that starts with `$` (e.g. `$AutoValueFoo` and `$$AutoValueFoo`) seems like  abstract classes that are generated to help getting final concrete one without `$`. Hence, the class without `$` sign (e.g. `AutoValue_Foo`) is the only option for creating a new instance. 

Correct me if my assumption is wrong.

**Comment by rharter** [comment]
I think @hakanbagci is correct here. Unless things have changed since my original extension architecture, the concrete classes guaranteed to be without a dollar sign, and extensions generate intermediate abstract classes with the dollar sign. The Auto value documentation requires that to instantiate your own instance of an auto value generated class.
