### ISSUE TITLE
Could not find com.ryan...

### ISSUE THREAD

**Issue by nucle** [rharter/auto-value-moshi#18]
Hi, first of all thank you for this library.
I added android-apt and apt 'com.ryanharter.auto.value:auto-value-moshi:0.2-SNAPSHOT' to my gradle build file. If i sync gradle i get the following message: 

Error:Could not find com.ryanharter.auto.value:auto-value-moshi:0.2-SNAPSHOT.
Searched in the following locations:
    file:/D:/android/studio/gradle/m2repository/com/ryanharter/auto/value/auto-value-moshi/0.2-SNAPSHOT/maven-metadata.xml
    file:/D:/android/studio/gradle/m2repository/com/ryanharter/auto/value/auto-value-moshi/0.2-SNAPSHOT/auto-value-moshi-0.2-SNAPSHOT.pom
    file:/D:/android/studio/gradle/m2repository/com/ryanharter/auto/value/auto-value-moshi/0.2-SNAPSHOT/auto-value-moshi-0.2-SNAPSHOT.jar
    https://jcenter.bintray.com/com/ryanharter/auto/value/auto-value-moshi/0.2-SNAPSHOT/maven-metadata.xml
.....    

I tried other apt libs and have no error messages. Can you help me.
Thank you

**Comment by JakeWharton** [comment]
Add:

``` groovy
repositories {
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```

**Comment by nucle** [comment]
Ah ok, now its working. Sorry.
Thank you!
