### ISSUE TITLE
Support default property values 

### ISSUE THREAD

**Issue by rharter** [rharter/auto-value-moshi#20]
After discussion with the Moshi creators, we should utilize the built in default value support via the builder.  There is a bit of complexity here, though, since you could have multiple static factory methods for builders, so I propose the introduction of `@JsonDefault` annotation that can be added to a single, possibly protected, static factory method returning `@AutoValue.Builder` to denote which one to use.  This makes the logic for generated construction as follows:
1. If there is a `@JsonDefault` annotated static factory method returning an `@AutoValue.Builder`, use it.
2. If there is only a single static factory method returning an `@AutoValue.Builder`, use it.
3. Use the constructor.

**Comment by atomd-zz** [comment]
+1

**Comment by ZakTaccardi** [comment]
> 1. If there is a @JsonDefault annotated static factory method returning an @AutoValue.Builder, use it.
> 2. If there is only a single static factory method returning an @AutoValue.Builder, use it.
> 3. Use the constructor.  

Looks like an excellent solution. For extra precaution, you could throw a compile time build error if multiple static factory builder methods exist without an `@JsonDefault` annotation. (this is low priority compared to fixing the issue at hand though)

**Comment by ZacSweers** [comment]
Anything others could do to help on this? Builders would work, but I don't think they should be required. Another alternative I was thinking of that would work with the adapter layer is to use `valueOf` and `parse`. 

``` java
@DefaultValue("1")
public int someProperty();

@DefaultValue("0.0")
public Double someDoubleProperty();

// Then in your generated adapter or constructor (if we can hook in to that)
int someProperty = Integer.parseInt("0")
Double someDoubleProperty = Double.valueOf("0.0")
```

Thoughts?

**Comment by JakeWharton** [comment]
The extension should call `parse` and emit `0` or `0.0` literals.

**Comment by JakeWharton** [comment]
Or just copy the string as a literal into the generated code and let `javac` sort it out...

**Comment by ZacSweers** [comment]
even better!

**Comment by veyndan** [comment]
I see that default property values has been supported in rharter/auto-value-gson#84. Are there any updates on it getting implemented for auto-value-moshi?

**Comment by ZacSweers** [comment]
I don't personally agree with that approach as it leaves you with a mutable adapter. I'd rather wait for something like builder support in the autovalue extensions API

**Comment by veyndan** [comment]
True, hopefully we'll see Builder support in the extension API soon. Any workarounds for the time being?

**Comment by Idolon-V** [comment]
@hzsweers I agree on your point about mutable adapter. As an alternate auto-value-moshi can provide a builder to build the immutable adapter in the following way:
```
public static JsonAdapter<Person> jsonAdapter(Moshi moshi) {
  return AutoValue_Person.MoshiJsonAdapter.builder()
        .setDefaultName("Bruce Wayne").build();
}
```

**Comment by saket** [comment]
Any updates on this? I have a usease where I need auto-value-moshi to initialize all Optional fields as `Optional.empty()` instead of null.

**Comment by ZacSweers** [comment]
I'd like to propose throwing a spike (more so than the one already here) in this and lean on AutoValue to support adding builders to the extensions API in https://github.com/google/auto/pull/501 or to use Moshi's native Kotlin support and its default values language feature

**Comment by ZacSweers** [comment]
Throwing the aforementioned spike and closing this out

**Comment by david-gang** [comment]
Hi @ZacSweers , it looks like autovalue is adding now an inspection api for builders. https://github.com/google/auto/issues/421

Would this mean that this issue will be feasible now?

**Comment by ZacSweers** [comment]
Yep! There is an open PR on auto-value-gson we'll pursue first to flesh out
how this looks

**Comment by david-gang** [comment]
hi @ZacSweers can this issue please be reopened to reflect that this is going to be worked on ?
