### ISSUE TITLE
Generated JsonAdapter.Factory doesn't handle base type

### ISSUE THREAD

**Issue by MariusVolkhart** [rharter/auto-value-moshi#3]
Given:

``` java
Moshi moshi = new Moshi.Builder()
  .add(Auto_ABV.typeAdapterFactory())
  .build();
moshi.adapter(ABV.class).fromJson(jsonString);
```

Will get:

``` java
java.lang.IllegalArgumentException: Cannot serialize abstract class com.package.ABV
  at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:58)
```

But expecting a new instance of `AutoValue_ABV.class`.

This issue is that the `create()` method of the generated `JsonAdapter.Factory` does `if (!(type instanceof ABV)) return null;` and since `ABV.class` is an instance of `Class` not `ABV`, the factory doesn't indicate it can handle the deserialization.

I have a solution that works, though it isn't pretty (yet). Right now it uses `com.squareup.moshi.Types#getRawType(Type)` reflectively (as it's package private). https://github.com/MariusVolkhart/auto-value-moshi/commit/554db9636d2cbe99a4367b35ececdd02d68b882e

Would appreciate feedback on whether or not to pursue this solution, either by requesting Moshi to make `getRawType(Type)` public or by bundling the code for it.

**Comment by rharter** [comment]
This should be fixed by #4
