### ISSUE TITLE
No AutoValueMoshiAdapterFactory is generated.

### ISSUE THREAD

**Issue by kamikat** [rharter/auto-value-moshi#31]
Using `android-apt:1.4` with `auto-value:1.2-rc1` + `auto-value-moshi:0.2.2` in my project.
Adapter sources are successfully generated but could not found `AutoValueMoshiAdapterFactrory` as described in project document.

**Comment by tadfisher** [comment]
This functionality is in HEAD but not in the latest release.

**Comment by rharter** [comment]
It's in the latest release as of 0.3.0 (yesterday).
