### ISSUE TITLE
MyClass.class.isAssignableFrom(type.getClass()) == false

### ISSUE THREAD

**Issue by julioromano** [rharter/auto-value-moshi#34]
When evaluating my Autovalue generated class (let's call it MyClass) the JsonAdapter.Factory create() method returns null instead of returning MyClass.jsonAdapter(moshi).

This happens because `MyClass.class.isAssignableFrom(type.getClass())` evaluates aways to false.

**Comment by julioromano** [comment]
I've submitted a tentative fix in #35

**Comment by ZacSweers** [comment]
Merging with #103
