### ISSUE TITLE
Cannot have a method with name "reader"

### ISSUE THREAD

**Issue by shoheikawano** [rharter/auto-value-moshi#36]
Hi @rharter, thanks a lot for your amazing library.

I'd like to report an issue I'm facing right now, which is I cannot have a field (or a method named) `reader`.

This is due to https://github.com/rharter/auto-value-moshi/blob/master/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java#L338

I'm guessing generated variable's name can be possibly modified not to let this kind of naming conflict happen, but what do you think about it?

**Comment by rharter** [comment]
I'll just have to update to use JavaPoet's namer, but it should be doable.

**Comment by shoheikawano** [comment]
@rharter Thanks for your quick fix! 🐹
