### ISSUE TITLE
Support custom package name and class name when auto-generate 'JsonAdapterFactory' class.

### ISSUE THREAD

**Issue by robxyy** [rharter/auto-value-moshi#39]
All modules generate 'com.ryanharter.auto.value.moshi.AutoValueMoshiAdapterFactory' individually, so when modules refer to each other, one module can only refer its own 'AutoValueMoshiAdapterFactory' and lost part of 'JsonAdapter'.

**Comment by rharter** [comment]
This has been fixed by #47.  Thanks!
