### ISSUE TITLE
Is List<?> serialization supported?

### ISSUE THREAD

**Issue by ZakTaccardi** [rharter/auto-value-moshi#42]
I have an `@AutoValue` class `Color` that de/serializes beautifully thanks to this extension.

However, I need to de/serialize `List<Color>`. Does this extension support this use case?

**Comment by rharter** [comment]
It should be fine, same way you'd normally do it with Moshi. Are you having issues?

**Comment by ZakTaccardi** [comment]
My bad, I'm not too familiar with how Moshi works yet but if Moshi automatically uses the the `Color` serializer provided by your extension via `moshi.adapter(Types.newParameterizedType(List.class, AutoValue_color.class));`  (yay reflection), then this is a non-issue

**Comment by rharter** [comment]
Yeah, so long as you add the generated `AutoValueMoshiTypeAdapterFactory` to Moshi as outlined [here](https://github.com/rharter/auto-value-moshi#usage) it will be able to figure all that out (no reflection needed).
