### ISSUE TITLE
Skipping NULL values.

### ISSUE THREAD

**Issue by imran0101** [rharter/auto-value-moshi#43]
Generated JsonAdapter skips null values. [AutoValueMoshiExtension](https://github.com/rharter/auto-value-moshi/blob/master/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java#L365)

Is there a way I can overcome this ?
I would like the field to gave a default value. It is not a primitive type.

**Comment by imran0101** [comment]
I have also tried custom FIELD @JsonQualifier.

The method is skipping even before custom Json adapter is called.

**Comment by rharter** [comment]
So the fields [do get](https://github.com/rharter/auto-value-moshi/blob/master/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java#L355) their default value for the type.  Are you saying you want a custom default type?

**Comment by imran0101** [comment]
Thanks for the quick reply.

Those are for primitive types. I have a server which is returning null for a field and I want to return a default value for the type. My type is Date.
Since any Null value is skipped in the MoshiExtension, @Nullable has become necessary.

if @JsonQualifier is allowed to execute before skipping, a work around is possible.
However I believe a @Default annotation will be really good to have.

What do you suggest?

**Comment by rharter** [comment]
Ahh, yes, that makes sense since the default value for `Object`'s is `null`.

I'm not sure of the best way to handle this, since that should really be the server's job (if null isn't a valid value, it shouldn't be the value).  I feel like this is slightly more complex than it seems.  For instance, what's the behavior if a field is missing vs. explicitly set to null.

@swankjesse @jakewharton Do you guys have any thoughts on the matter?

**Comment by imran0101** [comment]
A practice I have been following to avoid returning null if the field is missing or is null.
For example if List is null I choose to return Collections.emptyList().

Majority of the NPE issues are avoided this way. Since server is not in my control and can behave unexpectedly. if(!null) is too much boilerplate all over.

if a default value is provided skipping null or a field will be justified.

Instead of skipping Null token let the individual adapters handle Null.

This is just an example. It could be any object.

``` java
class StringAdapter extends JsonAdapter<String> {

    @Override public String fromJson(JsonReader reader) throws IOException {
      if (reader.peek() == JsonReader.Token.NULL) {
        reader.nextNull();
        return "default";
      }
      return reader.nextString();
    }

    @Override public void toJson(JsonWriter writer, String value) throws IOException {
      writer.value(value);
    }
  }
```

**Comment by swankjesse** [comment]
I don’t think this is the JSON adapter’s job. Instead, you should replace nulls with defaults in your Java model, and only encode it to JSON once you’ve done that.

**Comment by imran0101** [comment]
Is it possible to replace to defaults in the current AutoValue extension ?

default value for the current extension will always be [null](https://github.com/rharter/auto-value-moshi/blob/master/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java#L355).

**Comment by shoheikawano** [comment]
@mipreamble 

> default value for the current extension will always be null.

You're right. But I also agree with @swankjesse and I don’t think this is the JSON adapter’s job as well.

> Is it possible to replace to defaults in the current AutoValue extension?

Recently I had the same problem; I am using AutoValue extension, Moshi, and this library, and I wanted to make use all of them but also avoid annotating fields with `@Nullable` for actually nullable fields inside java models. 

Eventually I decided not to use this library to generate codes for de/serializing AutoValue class, but instead adding custom JsonAdapter to serialize JSON using [`@AutoValue.Builder` to specify default values](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#-specify-a-default-value-for-a-property) if any value from the server is `null`.

I'd like to know if there is any better way though! :bow:

**Comment by PaulWoitaschek** [comment]
I'm having this problem too and its quite annoying. I use this adapter to parse network models but I end up with lots of nullable lists in my auto value classes. I would like to replace the `@Nullable List<PoJo>` with a @NonNull list that defaults to `Collections.emtpyList()`.

**Comment by ZacSweers** [comment]
I think this falls under #20
