### ISSUE TITLE
Can't find an annotation @MoshiAdapterFactory

### ISSUE THREAD

**Issue by johnkil** [rharter/auto-value-moshi#48]
auto-value-moshi:0.4.0-rc2

**Comment by johnkil** [comment]
Need to add another line to the dependence

``` groovy
provided 'com.ryanharter.auto.value:auto-value-moshi:0.4.0-rc2'
```

**Comment by rharter** [comment]
Thanks, I've added it to the readme.

**Comment by ZakTaccardi** [comment]
what about pure java modules that do not have the `provided` scope? `compileOnly` would do the trick?

**Comment by JakeWharton** [comment]
yes
