### ISSUE TITLE
Error:(16, 20) error: cannot find symbol class AutoValueMoshi_JsonAdapterFactory

### ISSUE THREAD

**Issue by spectrl** [rharter/auto-value-moshi#54]
Trying to compile a pure java module and I have added 
`compileOnly 'com.ryanharter.auto.value:auto-value-moshi:0.4.0'`
 to my gradle file but it seems like my factory class isn't being generated...

This is the static method for my `JsonAdapterFactory` class:
`public static JsonAdapter.Factory create() {
        return new AutoValueMoshi_JsonAdapterFactory();
    }`

**Comment by spectrl** [comment]
Just tested using `provided` in my Android module as well and still can't get it to work.
Am I missing something obvious?

**Comment by spectrl** [comment]
Ignore me. I didn't have any static JsonAdapter methods in my model classes.
Could maybe make that clearer in the ReadMe?
It makes sense now, but the wording kinda suggests that the @MoshiAdapterFactory annotated abstract class can be used instead of the individual JsonAdapter methods in each model class - which are obviously also required in order for the factory to actually be generated.

**Comment by rharter** [comment]
Yeah, we get this issue a lot, so we should update the readme. I'm open to
suggestions if you want to submit a PR, otherwise I'll look at it
tomorrow.
