### ISSUE TITLE
Support creating list of AutoValue objects?

### ISSUE THREAD

**Issue by zoltish** [rharter/auto-value-moshi#56]
_Unless Ive missed it_; There doesnt seem to be a way to create a **list of objects** through the MoshiAdapter that you generate. 

What Im looking for:

```
@AutoValue
public static abstract class MyObject {
    public abstract String value();

    public static JsonAdapter<MyObject> jsonAdapterSingle(Moshi moshi){
        //return ... 
    }

    public static JsonAdapter<List<MyObject>> jsonAdapterList(Moshi moshi){
        //return ... 
    }
}
```

**Comment by serj-lotutovici** [comment]
Moshi has a built in JsonAdapter for lists, so there is no need for generating that. You easily check it:

```
Moshi moshi = new Moshi.Builder()
    .add(YourMoshiAdapterFactory.create())
    .build();

JsonAdapter<List<MyObject>> listAdapter = moshi.adapter(Types.newParameterizedType(List.class, MyObject.class));
```

**Comment by zoltish** [comment]
@serj-lotutovici Actually it works with the Factory, I attempted to make it work by only using the JsonAdapter(s). Thanks for helping me out!
