### ISSUE TITLE
Consider adding checkstyle to the project.

### ISSUE THREAD

**Issue by serj-lotutovici** [rharter/auto-value-moshi#62]
Why? -> code style consistency & helps avoid elementary mistakes (un-used imports and so on).
Which? -> the current code style in the project is similar to the one used in [moshi](https://github.com/square/moshi/), so I would suggest that one and also enforcing usage of a common code style. May the the one from [square](https://github.com/square/java-code-styles)?

What are your thoughts?

**Comment by rharter** [comment]
Sorry, I thought I sent my response to this but never hit send :)

I'm 100% in favor of this.  It's something I do on projects for clients, but never got to it with these ones.  I use Square's codestyle, so I'm definitely down for that.  Do you want to take this?

**Comment by serj-lotutovici** [comment]
Yup... pr coming right up...
