### ISSUE TITLE
Generates defect classes on unappropriate nullable annotations

### ISSUE THREAD

**Issue by PaulWoitaschek** [rharter/auto-value-moshi#65]
It just took me 1 hour to detect a stupid bug where my project wouldn't compile.

I had method of a primitive type annotated as `@Nullable`.
The generated adapter was checking

```
if(value.primitiveField() != null){
   ...
```

I think the appropriate behavior for this extension would be to simply ignore the annotation on nullable methods.

**Comment by rharter** [comment]
That's interesting, I would have expected compilation to fail since that isn't a valid annotation for primitive types.  What version of AV are you using?

**Comment by JakeWharton** [comment]
Seems like AutoValue should reject this with a compiler error before it
every reaches an extension.

**Comment by PaulWoitaschek** [comment]
Im using Auto Value 1.3. It actually broke my build but I just got 100 cryptic warnings about missing databinding classes.

**Comment by rharter** [comment]
Yeah, that's a different issue. https://code.google.com/p/android/issues/detail?id=208978

So it sounds like AutoValue **might** have been failing when you built, but I'm not sure where the `value.primitiveField() != null` would come from.

**Comment by ZacSweers** [comment]
Nothing further actionable here, but please comment if there is
