### ISSUE TITLE
Removing multiple calls to method

### ISSUE THREAD

**Issue by PaulWoitaschek** [rharter/auto-value-moshi#66]
I recently watched a talk by @JakeWharton about optimizing your code to not call getters multiple times when not necessary.

So it would be great to see that in the generated code so code like

``` java
if (value.name() != null) {
  writer.name("name");
  nameAdapter.toJson(writer, value.name());
}
```

will be simply

``` java
String name = value.name();
if (name != null) {
  writer.name("name");
  nameAdapter.toJson(writer, name);
}
```

**Comment by ZacSweers** [comment]
This seems like the micro-est of micro-optimizations when they're AV objects and not changing.

**Comment by ZacSweers** [comment]
Talked with jake separately - doesn't hurt to do it and free for us, should be pretty easy with `NameAllocator`.

**Comment by naturalwarren** [comment]
Nice. Would be great to seem this brought over to a-v-g as well.
