### ISSUE TITLE
Consider moving @MoshiAdapterFactory into it's own artifact

### ISSUE THREAD

**Issue by vanniktech** [rharter/auto-value-moshi#67]
It'd be awesome if `@MoshiAdapterFactory` would be in it's own artifact so that one does not have to use the following:

``` groovy
provided 'com.ryanharter.auto.value:auto-value-moshi:0.4.1'
```

to add the annotation to the classpath. The big disadvantage is that all of the other classes are also added to the class path (AutoValue components, possible Guava etc).

**Comment by serj-lotutovici** [comment]
Butterknife does something similar. There's an annotation artefact, that is shared between the runtime library and the annotation processor.
