### ISSUE TITLE
No generated MoshiJsonAdapters with Kotlin

### ISSUE THREAD

**Issue by Mauin** [rharter/auto-value-moshi#70]
When using auto-value-moshi with Kotlin, it seems like kapt is not generating any sources related to Moshi. The basic AutoValue classes are being generated, just nothing related to Moshi.

Is this a known issue? Let me know if I can provide more details.

**Comment by serj-lotutovici** [comment]
Can you provide an example class that show cases the issue?

**Comment by rharter** [comment]
Check that you're creating a public static method returning a factory. With
Kotlin's companion objects you'd have to use `@JvmStatic` so it creates an
actual static method.

**Comment by Mauin** [comment]
Ah thanks so much @rharter that did the trick. Should this maybe go into the README as a note for Kotlin users who still want to use AutoValue with it's extensions?

**Comment by ZacSweers** [comment]
I think the issue is good enough posterity for now
