### ISSUE TITLE
AutoValue Parcel Extension Error

### ISSUE THREAD

**Issue by kalaiselvan369** [rharter/auto-value-moshi#75]
Error:(13, 17) error: Extension com.ryanharter.auto.value.parcel.AutoValueParcelExtension wants to consume a property that does not exist: writeToParcel

Above error occurs when I used both @AutoValue and @MoshiAdapterFactory in single class that also implements parcelable and JsonAdapter.Factory.

Kindly help me.

**Comment by rharter** [comment]
An AdapterFactory is, by definition, not a value type, nor part of a value type, so it seems weird that you'd also include that.  I'd recommend moving that to a separate class (also, unless you only have on `@AutoValue` class, in which case you don't really need the factory, it would be weird to have the factory **in** one of your models)

**Comment by kalaiselvan369** [comment]
@rharter Understood now. Thanks.
