### ISSUE TITLE
Generics bug with "? extends _____"

### ISSUE THREAD

**Issue by ZacSweers** [rharter/auto-value-moshi#77]
If I have a list like so:

`List<? extends Thing>`

The generated code fails to compile because it looks like this:

`moshi.adapter(Types.newParameterizedType(List.class, ? extends Thing.class));`

**Comment by swankjesse** [comment]
You can make `? extends Thing` with `Types.subtypeOf(Thing.class)`.

http://square.github.io/moshi/1.x/moshi/com/squareup/moshi/Types.html#subtypeOf-java.lang.reflect.Type-
