### ISSUE TITLE
Issue serialising abstract class

### ISSUE THREAD

**Issue by richarth** [rharter/auto-value-moshi#79]
I'm trying to use Retrofit 2, AutoValue, Moshi and the AutoValue: Moshi Extension in combination and I've run into the Cannot serialize abstract class issue.

I've created a POJO myself ([Movie2](https://gist.github.com/richarth/476f16f63a80ef064752b88532623996#file-movie2-java)) and a unit test which passes without problem for converting JSON to an instance of my POJO. 

I have another unit test to verify that my JSON is converted to an instance of my POJO ([Movie](https://gist.github.com/richarth/476f16f63a80ef064752b88532623996#file-movie-java)) created using AutoValue.  Unfortunately this test always fails with the following stack trace:

```
java.lang.IllegalArgumentException: Cannot serialize abstract class com.appassembla.android.popularmovies.data.Movie

	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:59)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:94)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:61)
```
I've created a Gist with some [sample code here](https://gist.github.com/richarth/476f16f63a80ef064752b88532623996). It includes my tests and the dependencies in my app's build.gradle.  Let me know if you need anything else.

**Comment by rharter** [comment]
You need to register the generated Type adapter with Moshi in order for it to deserialize the component.

**Comment by richarth** [comment]
I created and added a factory as well as implementing the jsonAdapter method in my POJO and that fixed it.

Many thanks for the prompt assistance.
