### ISSUE TITLE
Factory annotation processor picks wrong method

### ISSUE THREAD

**Issue by mik9** [rharter/auto-value-moshi#82]
If model have a method with parameterized return type defined before moshi's typeAdapter method the annotation processor picks wrong method for factory generation.
Example:
```
import com.google.auto.value.AutoValue;
import com.google.gson.Gson;
import com.google.gson.TypeAdapter;
import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.Moshi;

@AutoValue
public abstract class Section {
    public abstract int id();

    public static TypeAdapter<Section> typeAdapter(Gson gson) {
        return new AutoValue_Section.GsonTypeAdapter(gson);
    }

    public static JsonAdapter<Section> jsonAdapter(Moshi moshi) {
        return new AutoValue_Section.MoshiJsonAdapter(moshi);
    }
}
```

**Comment by ZacSweers** [comment]
Can you share an example of the output or trace?

**Comment by mik9** [comment]
Sorry, I didn't saved screenshots (I can do this later), but I can point to line that probably cause error:
https://github.com/rharter/auto-value-moshi/blob/master/auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiAdapterFactoryProcessor.java#L240

It picks any method which type is ParameterizedTypeName and does not checks what the type is.

**Comment by JakeWharton** [comment]
Wow, yep. Should be an easy fix.
