### ISSUE TITLE
Support for package-private jsonAdapter method

### ISSUE THREAD

**Issue by nedtwigg** [rharter/auto-value-moshi#87]
auto-value-moshi requires a method like this:

```java
public static JsonAdapter<MyAutoValueClass> jsonAdapter(Moshi moshi) { ... }
```

Are you open to a PR which would allow this?

```java
static JsonAdapter<MyAutoValueClass> jsonAdapter(Moshi moshi) { ... }
```

With Java 9 modularity coming, I'd like the option to use Moshi as an implementation detail which is invisible to client code.

**Comment by JakeWharton** [comment]
That would require all your model objects be in the same package. Is that
ok? Compilation would fail otherwise, which seems like reasonable behavior.

**Comment by rharter** [comment]
That's only the case if you're using the MoshiAdapterFactory, right?  If
accessing the adapters manually or another way then they could be in
different packages.

**Comment by JakeWharton** [comment]
Yeah. I was thinking about models that referenced other models in other
packages specifically.

I still think it's reasonable to allow.

**Comment by rharter** [comment]
I agree, seems like a simple enough option that doesn't hinder any current
functionality.

**Comment by ZacSweers** [comment]
Eyeballed https://github.com/nedtwigg/auto-value-moshi/commit/cd905acdd0ab701048c19a1e6034dba3ee395319

I think that mostly works, but we should do extra checks at compile-time to basically make sure we're only including models from the same package if we do this, otherwise you could get confusing error messages about not generating anything if you have multiple factories in different packages

**Comment by nedtwigg** [comment]
Looks like there's been quite a bit of really useful stuff since `0.4.5`: https://github.com/rharter/auto-value-moshi/compare/0.4.5...master

In addition to this issue, upgrading to AutoValue 1.6 and implementing `net.ltgt.gradle.incap.IncrementalAnnotationProcessorType.AGGREGATING` would be big wins.  I know there's always more I try to stuff into my releases, but it would be really cool to get an `0.4.6` as-is out on MavenCentral.  It's 0.x stuff, no warranty expected :)

**Comment by nedtwigg** [comment]
WAAAHOOOO!!!  Thanks so much for 0.4.6!  This is such a useful library, great to see it shipping again :)
